spring:
  application:
    name: DevicesAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/devicesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    com:
      devicesapi: DEBUG

    org:
      springframework:
        web: DEBUG

    hibernate:
      SQL: DEBUG

    type:
      descriptor:
      sql:
      BasicBinder: TRACE